### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1139]
https://sentry.io/eviction-lab/eviction-lab/issues/534833876/

```
TypeError: Cannot read property '0' of undefined
  at t.updateHighlights (/tool/main.66f2435d23a377ae6075.bundle.js:1:1468680)
  at t.updateMapData (/tool/main.66f2435d23a377ae6075.bundle.js:1:1471616)
  at t.onMapReady (/tool/main.66f2435d23a377ae6075.bundle.js:1:1467289)
  at Object.handleEvent (/tool/main.66f2435d23a377ae6075.bundle.js:1:1487055)
  at Object.handleEvent (/tool/main.66f2435d23a377ae6075.bundle.js:1:591748)
...
(22 additional frame(s) were not displayed)
```

**Comment by Lane** [comment]
This error happens when opening the map from an embed link with a selected location.

To replicate, click on the eviction lab logo in the embed on this page: https://action-lab.org/eviction/
