### ISSUE TITLE
TypeError: e[this.selectedIndex] is undefined

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1175]
https://sentry.io/eviction-lab/eviction-lab/issues/549462136/

```
TypeError: e[this.selectedIndex] is undefined
  at cDNt/La</t.prototype.onkeypress (/tool/main.7ed3450fa33323f9c3bb.bundle.js:1:1034955)
  at bg/< (/tool/main.7ed3450fa33323f9c3bb.bundle.js:1:1550759)
  at handleEvent (/tool/main.7ed3450fa33323f9c3bb.bundle.js:1:591735)
  at handleEvent (/tool/main.7ed3450fa33323f9c3bb.bundle.js:1:603035)
  at Zi (/tool/main.7ed3450fa33323f9c3bb.bundle.js:1:563024)
...
(10 additional frame(s) were not displayed)
```

**Comment by Lane** [comment]
issue no longer appearing in logs, closing
